### ISSUE TITLE
dellapena das pena

### ISSUE THREAD

**Issue by chuismiguel** [gdellapenna/UPMurphi#2]
help im failing

lex.yy.cc: In member function ‘virtual int yyFlexLexer::yylex()’:
lex.yy.cc:1166:18: error: no match for ‘operator=’ (operand types are ‘std::istream’ {aka ‘std::basic_istream<char>’} and ‘std::istream*’ {aka ‘std::basic_istream<char>*’})
 1166 |    yyin = & std::cin;
      |                  ^~~
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:625:7: note: candidate: ‘std::basic_istream<_CharT, _Traits>& std::basic_istream<_CharT, _Traits>::operator=(std::basic_istream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  625 |       operator=(basic_istream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/istream:625:33: note:   no known conversion for argument 1 from ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::basic_istream<char>&&’
  625 |       operator=(basic_istream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1169:19: error: no match for ‘operator=’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’})
 1169 |    yyout = & std::cout;
      |                   ^~~~
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:408:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator=(std::basic_ostream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  408 |       operator=(basic_ostream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/ostream:408:33: note:   no known conversion for argument 1 from ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’} to ‘std::basic_ostream<char>&&’
  408 |       operator=(basic_ostream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1818:46: error: cannot convert ‘std::istream’ {aka ‘std::basic_istream<char>’} to ‘std::istream*’ {aka ‘std::basic_istream<char>*’} in assignment
 1818 |    YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
      |                                              ^~~~
      |                                              |
      |                                              std::istream {aka std::basic_istream<char>}
lex.yy.cc: In constructor ‘yyFlexLexer::yyFlexLexer(std::istream*, std::ostream*)’:
lex.yy.cc:1929:75: error: ‘std::basic_istream<_CharT, _Traits>::basic_istream() [with _CharT = char; _Traits = std::char_traits<char>]’ is protected within this context
 1929 | yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
      |                                                                           ^
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:606:7: note: declared protected here
  606 |       basic_istream()
      |       ^~~~~~~~~~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1929:75: error: ‘std::basic_ostream<_CharT, _Traits>::basic_ostream() [with _CharT = char; _Traits = std::char_traits<char>]’ is protected within this context
 1929 | yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
      |                                                                           ^
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:390:7: note: declared protected here
  390 |       basic_ostream()
      |       ^~~~~~~~~~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1931:9: error: no match for ‘operator=’ (operand types are ‘std::istream’ {aka ‘std::basic_istream<char>’} and ‘std::istream*’ {aka ‘std::basic_istream<char>*’})
 1931 |  yyin = arg_yyin;
      |         ^~~~~~~~
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:625:7: note: candidate: ‘std::basic_istream<_CharT, _Traits>& std::basic_istream<_CharT, _Traits>::operator=(std::basic_istream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  625 |       operator=(basic_istream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/istream:625:33: note:   no known conversion for argument 1 from ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::basic_istream<char>&&’
  625 |       operator=(basic_istream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1932:10: error: no match for ‘operator=’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’})
 1932 |  yyout = arg_yyout;
      |          ^~~~~~~~~
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:408:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator=(std::basic_ostream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  408 |       operator=(basic_ostream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/ostream:408:33: note:   no known conversion for argument 1 from ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’} to ‘std::basic_ostream<char>&&’
  408 |       operator=(basic_ostream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘virtual void yyFlexLexer::switch_streams(std::istream*, std::ostream*)’:
lex.yy.cc:1978:11: error: no match for ‘operator=’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’})
 1978 |   yyout = new_out;
      |           ^~~~~~~
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:408:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator=(std::basic_ostream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  408 |       operator=(basic_ostream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/ostream:408:33: note:   no known conversion for argument 1 from ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’} to ‘std::basic_ostream<char>&&’
  408 |       operator=(basic_ostream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘virtual int yyFlexLexer::LexerInput(char*, int)’:
lex.yy.cc:1987:11: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1987 |  if ( yyin->eof() || yyin->fail() )
      |           ^~
lex.yy.cc:1987:26: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1987 |  if ( yyin->eof() || yyin->fail() )
      |                          ^~
lex.yy.cc:1991:6: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1991 |  yyin->get( buf[0] );
      |      ^~
lex.yy.cc:1993:11: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1993 |  if ( yyin->eof() )
      |           ^~
lex.yy.cc:1996:11: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1996 |  if ( yyin->bad() )
      |           ^~
lex.yy.cc: In member function ‘virtual void yyFlexLexer::LexerOutput(const char*, int)’:
lex.yy.cc:2013:14: error: base operand of ‘->’ has non-pointer type ‘std::ostream’ {aka ‘std::basic_ostream<char>’}
 2013 |  (void) yyout->write( buf, size );
      |              ^~
lex.yy.cc: In member function ‘virtual void yyFlexLexer::yyrestart(std::istream*)’:
lex.yy.cc:2333:37: error: cannot convert ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::istream&’ {aka ‘std::basic_istream<char>&’}
 2333 |  yy_init_buffer( YY_CURRENT_BUFFER, input_file );
      |                                     ^~~~~~~~~~
      |                                     |
      |                                     std::istream* {aka std::basic_istream<char>*}
In file included from lex.yy.cc:323,
                 from pddl+.yacc:1423:
/usr/include/FlexLexer.h:156:58: note:   initializing argument 2 of ‘void yyFlexLexer::yy_init_buffer(yy_buffer_state*, std::istream&)’
  156 |   void yy_init_buffer( yy_buffer_state* b, std::istream& s );
      |                                            ~~~~~~~~~~~~~~^
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘void yyFlexLexer::yy_load_buffer_state()’:
lex.yy.cc:2376:35: error: no match for ‘operator=’ (operand types are ‘std::istream’ {aka ‘std::basic_istream<char>’} and ‘std::istream*’ {aka ‘std::basic_istream<char>*’})
 2376 |  yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
      |                                   ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:625:7: note: candidate: ‘std::basic_istream<_CharT, _Traits>& std::basic_istream<_CharT, _Traits>::operator=(std::basic_istream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  625 |       operator=(basic_istream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/istream:625:33: note:   no known conversion for argument 1 from ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::basic_istream<char>&&’
  625 |       operator=(basic_istream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘virtual yy_buffer_state* yyFlexLexer::yy_create_buffer(std::istream*, int)’:
lex.yy.cc:2405:21: error: cannot convert ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::istream&’ {aka ‘std::basic_istream<char>&’}
 2405 |  yy_init_buffer( b, file );
      |                     ^~~~
      |                     |
      |                     std::istream* {aka std::basic_istream<char>*}
In file included from lex.yy.cc:323,
                 from pddl+.yacc:1423:
/usr/include/FlexLexer.h:156:58: note:   initializing argument 2 of ‘void yyFlexLexer::yy_init_buffer(yy_buffer_state*, std::istream&)’
  156 |   void yy_init_buffer( yy_buffer_state* b, std::istream& s );
      |                                            ~~~~~~~~~~~~~~^
In file included from pddl+.yacc:1423:
lex.yy.cc: At global scope:
lex.yy.cc:22:25: error: no declaration matches ‘void yyFlexLexer::yy_init_buffer(YY_BUFFER_STATE, std::istream*)’
   22 |     #define yyFlexLexer yyFlexLexer
      |                         ^~~~~~~~~~~
lex.yy.cc:2433:10: note: in expansion of macro ‘yyFlexLexer’
 2433 |     void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
      |          ^~~~~~~~~~~
In file included from lex.yy.cc:323,
                 from pddl+.yacc:1423:
/usr/include/FlexLexer.h:156:8: note: candidate is: ‘void yyFlexLexer::yy_init_buffer(yy_buffer_state*, std::istream&)’
  156 |   void yy_init_buffer( yy_buffer_state* b, std::istream& s );
      |        ^~~~~~~~~~~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:22:25: note: ‘class yyFlexLexer’ defined here
   22 |     #define yyFlexLexer yyFlexLexer
      |                         ^~~~~~~~~~~
make[1]: *** [Makefile:27: pddl+.o] Error 1
make[1]: Leaving directory '/home/chuismi/Desktop/robotica/tercero/segundocuat/planificacion/UPMurphi/src/UPMurphi_parser'
make: *** [Makefile:7: pddl2upm] Error 2

**Comment by gbernalr** [comment]
i had the same error, but i did not fix it, help us delapena

**Comment by gdellapenna** [comment]
Hi. Unfortunately, the Murphi core, which UPMurphi builds on, is rather old and has not been updated, so maintaining UPMurphi would require us a complete rewriting of the base code, which is currently impossible. UPMurphi is currently unmanintained and we cannot fix any issue. If you still want to try it, refer to the troubleshoot.txt for the correct versions of the libraries and tools that were used in our last successful compilations. They *may* work. Thanks for your interest in UPMurphi, we hope to come back soon with a new, updated tool.
